// generated by sim/z8002/gen_decode.py from MAME 0.288 z8000tbl.hxx -- do not edit
localparam logic [5:0] C_NOP = 6'd0;
localparam logic [5:0] C_ALU = 6'd1;
localparam logic [5:0] C_MUL = 6'd2;
localparam logic [5:0] C_DIV = 6'd3;
localparam logic [5:0] C_UN = 6'd4;
localparam logic [5:0] C_BITDYN = 6'd5;
localparam logic [5:0] C_STORE = 6'd6;
localparam logic [5:0] C_EX = 6'd7;
localparam logic [5:0] C_PUSH = 6'd8;
localparam logic [5:0] C_POP = 6'd9;
localparam logic [5:0] C_LDA = 6'd10;
localparam logic [5:0] C_JP = 6'd11;
localparam logic [5:0] C_CALL = 6'd12;
localparam logic [5:0] C_RET = 6'd13;
localparam logic [5:0] C_CALR = 6'd14;
localparam logic [5:0] C_JR = 6'd15;
localparam logic [5:0] C_DJNZ = 6'd16;
localparam logic [5:0] C_IRET = 6'd17;
localparam logic [5:0] C_LDPS = 6'd18;
localparam logic [5:0] C_HALT = 6'd19;
localparam logic [5:0] C_DIEI = 6'd20;
localparam logic [5:0] C_LDCTL = 6'd21;
localparam logic [5:0] C_MREQ = 6'd22;
localparam logic [5:0] C_TRAPREQ = 6'd23;
localparam logic [5:0] C_FLAGS = 6'd24;
localparam logic [5:0] C_SHIFT = 6'd25;
localparam logic [5:0] C_DAB = 6'd26;
localparam logic [5:0] C_EXTS = 6'd27;
localparam logic [5:0] C_TCC = 6'd28;
localparam logic [5:0] C_LDK = 6'd29;
localparam logic [5:0] C_LDBS = 6'd30;
localparam logic [5:0] C_RXDB = 6'd31;
localparam logic [5:0] C_BLK = 6'd32;
localparam logic [5:0] C_TR = 6'd33;
localparam logic [5:0] C_LDM = 6'd34;
localparam logic [5:0] C_IO = 6'd35;
localparam logic [5:0] C_EPU = 6'd36;
localparam logic [4:0] A_ADD = 5'd0;
localparam logic [4:0] A_ADC = 5'd1;
localparam logic [4:0] A_SUB = 5'd2;
localparam logic [4:0] A_SBC = 5'd3;
localparam logic [4:0] A_OR = 5'd4;
localparam logic [4:0] A_AND = 5'd5;
localparam logic [4:0] A_XOR = 5'd6;
localparam logic [4:0] A_CP = 5'd7;
localparam logic [4:0] A_LD = 5'd8;
localparam logic [4:0] A_COM = 5'd9;
localparam logic [4:0] A_NEG = 5'd10;
localparam logic [4:0] A_TEST = 5'd11;
localparam logic [4:0] A_TSET = 5'd12;
localparam logic [4:0] A_CLR = 5'd13;
localparam logic [4:0] A_LDIMM = 5'd14;
localparam logic [4:0] A_CPIMM = 5'd15;
localparam logic [4:0] A_INC = 5'd16;
localparam logic [4:0] A_DEC = 5'd17;
localparam logic [4:0] A_RES = 5'd18;
localparam logic [4:0] A_SET = 5'd19;
localparam logic [4:0] A_BIT = 5'd20;
localparam logic [3:0] M_NONE = 4'd0;
localparam logic [3:0] M_IMM = 4'd1;
localparam logic [3:0] M_IR = 4'd2;
localparam logic [3:0] M_DA = 4'd3;
localparam logic [3:0] M_X = 4'd4;
localparam logic [3:0] M_R = 4'd5;
localparam logic [3:0] M_REL = 4'd6;
localparam logic [3:0] M_BA = 4'd7;
localparam logic [3:0] M_BX = 4'd8;

function automatic logic [34:0] z8k_dec(input logic [15:0] op);
    logic [7:0] lo;
    lo = op[7:0];
    z8k_dec = 35'h8028000;
    case (op[15:8])
        8'h00: begin
            if (lo <= 8'h0f) z8k_dec = 35'he080104;
            else z8k_dec = 35'he080200;
        end
        8'h01: begin
            if (lo <= 8'h0f) z8k_dec = 35'he0a0104;
            else z8k_dec = 35'he0a0200;
        end
        8'h02: begin
            if (lo <= 8'h0f) z8k_dec = 35'he082104;
            else z8k_dec = 35'he082200;
        end
        8'h03: begin
            if (lo <= 8'h0f) z8k_dec = 35'he0a2104;
            else z8k_dec = 35'he0a2200;
        end
        8'h04: begin
            if (lo <= 8'h0f) z8k_dec = 35'he084104;
            else z8k_dec = 35'he084200;
        end
        8'h05: begin
            if (lo <= 8'h0f) z8k_dec = 35'he0a4104;
            else z8k_dec = 35'he0a4200;
        end
        8'h06: begin
            if (lo <= 8'h0f) z8k_dec = 35'he085104;
            else z8k_dec = 35'he085200;
        end
        8'h07: begin
            if (lo <= 8'h0f) z8k_dec = 35'he0a5104;
            else z8k_dec = 35'he0a5200;
        end
        8'h08: begin
            if (lo <= 8'h0f) z8k_dec = 35'he086104;
            else z8k_dec = 35'he086200;
        end
        8'h09: begin
            if (lo <= 8'h0f) z8k_dec = 35'he0a6104;
            else z8k_dec = 35'he0a6200;
        end
        8'h0a: begin
            if (lo <= 8'h0f) z8k_dec = 35'he087104;
            else z8k_dec = 35'he087200;
        end
        8'h0b: begin
            if (lo <= 8'h0f) z8k_dec = 35'he0a7104;
            else z8k_dec = 35'he0a7200;
        end
        8'h0c: begin
            if (lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h18209210;
            else if (lo == 8'h11 || lo == 8'h21 || lo == 8'h31 || lo == 8'h41 || lo == 8'h51 || lo == 8'h61 || lo == 8'h71 || lo == 8'h81 || lo == 8'h91 || lo == 8'ha1 || lo == 8'hb1 || lo == 8'hc1 || lo == 8'hd1 || lo == 8'he1 || lo == 8'hf1) z8k_dec = 35'h1620f204;
            else if (lo == 8'h12 || lo == 8'h22 || lo == 8'h32 || lo == 8'h42 || lo == 8'h52 || lo == 8'h62 || lo == 8'h72 || lo == 8'h82 || lo == 8'h92 || lo == 8'ha2 || lo == 8'hb2 || lo == 8'hc2 || lo == 8'hd2 || lo == 8'he2 || lo == 8'hf2) z8k_dec = 35'h1820a200;
            else if (lo == 8'h14 || lo == 8'h24 || lo == 8'h34 || lo == 8'h44 || lo == 8'h54 || lo == 8'h64 || lo == 8'h74 || lo == 8'h84 || lo == 8'h94 || lo == 8'ha4 || lo == 8'hb4 || lo == 8'hc4 || lo == 8'hd4 || lo == 8'he4 || lo == 8'hf4) z8k_dec = 35'h1020b200;
            else if (lo == 8'h15 || lo == 8'h25 || lo == 8'h35 || lo == 8'h45 || lo == 8'h55 || lo == 8'h65 || lo == 8'h75 || lo == 8'h85 || lo == 8'h95 || lo == 8'ha5 || lo == 8'hb5 || lo == 8'hc5 || lo == 8'hd5 || lo == 8'he5 || lo == 8'hf5) z8k_dec = 35'he20e204;
            else if (lo == 8'h16 || lo == 8'h26 || lo == 8'h36 || lo == 8'h46 || lo == 8'h56 || lo == 8'h66 || lo == 8'h76 || lo == 8'h86 || lo == 8'h96 || lo == 8'ha6 || lo == 8'hb6 || lo == 8'hc6 || lo == 8'hd6 || lo == 8'he6 || lo == 8'hf6) z8k_dec = 35'h1620c200;
            else if (lo == 8'h18 || lo == 8'h28 || lo == 8'h38 || lo == 8'h48 || lo == 8'h58 || lo == 8'h68 || lo == 8'h78 || lo == 8'h88 || lo == 8'h98 || lo == 8'ha8 || lo == 8'hb8 || lo == 8'hc8 || lo == 8'hd8 || lo == 8'he8 || lo == 8'hf8) z8k_dec = 35'h1020d200;
            else z8k_dec = 35'h8028000;
        end
        8'h0d: begin
            if (lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h18229200;
            else if (lo == 8'h11 || lo == 8'h21 || lo == 8'h31 || lo == 8'h41 || lo == 8'h51 || lo == 8'h61 || lo == 8'h71 || lo == 8'h81 || lo == 8'h91 || lo == 8'ha1 || lo == 8'hb1 || lo == 8'hc1 || lo == 8'hd1 || lo == 8'he1 || lo == 8'hf1) z8k_dec = 35'h1622f204;
            else if (lo == 8'h12 || lo == 8'h22 || lo == 8'h32 || lo == 8'h42 || lo == 8'h52 || lo == 8'h62 || lo == 8'h72 || lo == 8'h82 || lo == 8'h92 || lo == 8'ha2 || lo == 8'hb2 || lo == 8'hc2 || lo == 8'hd2 || lo == 8'he2 || lo == 8'hf2) z8k_dec = 35'h1822a200;
            else if (lo == 8'h14 || lo == 8'h24 || lo == 8'h34 || lo == 8'h44 || lo == 8'h54 || lo == 8'h64 || lo == 8'h74 || lo == 8'h84 || lo == 8'h94 || lo == 8'ha4 || lo == 8'hb4 || lo == 8'hc4 || lo == 8'hd4 || lo == 8'he4 || lo == 8'hf4) z8k_dec = 35'h1022b200;
            else if (lo == 8'h15 || lo == 8'h25 || lo == 8'h35 || lo == 8'h45 || lo == 8'h55 || lo == 8'h65 || lo == 8'h75 || lo == 8'h85 || lo == 8'h95 || lo == 8'ha5 || lo == 8'hb5 || lo == 8'hc5 || lo == 8'hd5 || lo == 8'he5 || lo == 8'hf5) z8k_dec = 35'h1622e204;
            else if (lo == 8'h16 || lo == 8'h26 || lo == 8'h36 || lo == 8'h46 || lo == 8'h56 || lo == 8'h66 || lo == 8'h76 || lo == 8'h86 || lo == 8'h96 || lo == 8'ha6 || lo == 8'hb6 || lo == 8'hc6 || lo == 8'hd6 || lo == 8'he6 || lo == 8'hf6) z8k_dec = 35'h1622c200;
            else if (lo == 8'h18 || lo == 8'h28 || lo == 8'h38 || lo == 8'h48 || lo == 8'h58 || lo == 8'h68 || lo == 8'h78 || lo == 8'h88 || lo == 8'h98 || lo == 8'ha8 || lo == 8'hb8 || lo == 8'hc8 || lo == 8'hd8 || lo == 8'he8 || lo == 8'hf8) z8k_dec = 35'h1022d200;
            else if (lo == 8'h19 || lo == 8'h29 || lo == 8'h39 || lo == 8'h49 || lo == 8'h59 || lo == 8'h69 || lo == 8'h79 || lo == 8'h89 || lo == 8'h99 || lo == 8'ha9 || lo == 8'hb9 || lo == 8'hc9 || lo == 8'hd9 || lo == 8'he9 || lo == 8'hf9) z8k_dec = 35'h18428104;
            else z8k_dec = 35'h8028000;
        end
        8'h0e: begin
             z8k_dec = 35'h15228001;
        end
        8'h0f: begin
             z8k_dec = 35'h15228001;
        end
        8'h10: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1c0c7108;
            else z8k_dec = 35'h1c0c7200;
        end
        8'h11: begin
            if (lo <= 8'h10) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h28448200;
        end
        8'h12: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1c0c2108;
            else z8k_dec = 35'h1c0c2200;
        end
        8'h13: begin
            if (lo <= 8'h10) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h1a428200;
        end
        8'h14: begin
            if (lo <= 8'h0f) z8k_dec = 35'h160c8108;
            else z8k_dec = 35'h160c8200;
        end
        8'h15: begin
            if (lo <= 8'h10) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h264c8500;
        end
        8'h16: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1c0c0108;
            else z8k_dec = 35'h1c0c0200;
        end
        8'h17: begin
            if (lo <= 8'h10) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h184a8200;
        end
        8'h18: begin
            if (lo <= 8'h0f) z8k_dec = 35'h234148108;
            else z8k_dec = 35'h234148500;
        end
        8'h19: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8c128104;
            else z8k_dec = 35'h8c128200;
        end
        8'h1a: begin
            if (lo <= 8'h0f) z8k_dec = 35'h5d01c8108;
            else z8k_dec = 35'h5d01c8200;
        end
        8'h1b: begin
            if (lo <= 8'h0f) z8k_dec = 35'hd61a8104;
            else z8k_dec = 35'hd61a8200;
        end
        8'h1c: begin
            if (lo == 8'h11 || lo == 8'h21 || lo == 8'h31 || lo == 8'h41 || lo == 8'h51 || lo == 8'h61 || lo == 8'h71 || lo == 8'h81 || lo == 8'h91 || lo == 8'ha1 || lo == 8'hb1 || lo == 8'hc1 || lo == 8'hd1 || lo == 8'he1 || lo == 8'hf1) z8k_dec = 35'h17128214;
            else if (lo == 8'h18 || lo == 8'h28 || lo == 8'h38 || lo == 8'h48 || lo == 8'h58 || lo == 8'h68 || lo == 8'h78 || lo == 8'h88 || lo == 8'h98 || lo == 8'ha8 || lo == 8'hb8 || lo == 8'hc8 || lo == 8'hd8 || lo == 8'he8 || lo == 8'hf8) z8k_dec = 35'h1a24b200;
            else if (lo == 8'h19 || lo == 8'h29 || lo == 8'h39 || lo == 8'h49 || lo == 8'h59 || lo == 8'h69 || lo == 8'h79 || lo == 8'h89 || lo == 8'h99 || lo == 8'ha9 || lo == 8'hb9 || lo == 8'hc9 || lo == 8'hd9 || lo == 8'he9 || lo == 8'hf9) z8k_dec = 35'h17128204;
            else z8k_dec = 35'h8028000;
        end
        8'h1d: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h16348200;
        end
        8'h1e: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h145a8200;
        end
        8'h1f: begin
            if (lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h14628200;
            else z8k_dec = 35'h8028000;
        end
        8'h20: begin
            if (lo <= 8'h0f) z8k_dec = 35'he088104;
            else z8k_dec = 35'he088200;
        end
        8'h21: begin
            if (lo <= 8'h0f) z8k_dec = 35'he0a8104;
            else z8k_dec = 35'he0a8200;
        end
        8'h22: begin
            if (lo <= 8'h0f) z8k_dec = 35'h14292504;
            else z8k_dec = 35'h16212200;
        end
        8'h23: begin
            if (lo <= 8'h0f) z8k_dec = 35'h142b2504;
            else z8k_dec = 35'h16232200;
        end
        8'h24: begin
            if (lo <= 8'h0f) z8k_dec = 35'h14293504;
            else z8k_dec = 35'h16213200;
        end
        8'h25: begin
            if (lo <= 8'h0f) z8k_dec = 35'h142b3504;
            else z8k_dec = 35'h16233200;
        end
        8'h26: begin
            if (lo <= 8'h0f) z8k_dec = 35'h14294504;
            else z8k_dec = 35'h10214200;
        end
        8'h27: begin
            if (lo <= 8'h0f) z8k_dec = 35'h142b4504;
            else z8k_dec = 35'h10234200;
        end
        8'h28: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h16210200;
        end
        8'h29: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h16230200;
        end
        8'h2a: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h16211200;
        end
        8'h2b: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h16231200;
        end
        8'h2c: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h18388200;
        end
        8'h2d: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h183a8200;
        end
        8'h2e: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h10308200;
        end
        8'h2f: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h10328200;
        end
        8'h30: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1c088604;
            else z8k_dec = 35'h1c088704;
        end
        8'h31: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1c0a8604;
            else z8k_dec = 35'h1c0a8704;
        end
        8'h32: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1c308604;
            else z8k_dec = 35'h1c308704;
        end
        8'h33: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1c328604;
            else z8k_dec = 35'h1c328704;
        end
        8'h34: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1e528004;
            else z8k_dec = 35'h1e528014;
        end
        8'h35: begin
            if (lo <= 8'h0f) z8k_dec = 35'h220c8604;
            else z8k_dec = 35'h220c8704;
        end
        8'h36: begin
            if (lo == 8'h00) z8k_dec = 35'h4ba8010;
            else z8k_dec = 35'h14028000;
        end
        8'h37: begin
            if (lo <= 8'h0f) z8k_dec = 35'h22348604;
            else z8k_dec = 35'h22348704;
        end
        8'h38: begin
             z8k_dec = 35'h14028000;
        end
        8'h39: begin
            if (lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h18928202;
            else z8k_dec = 35'h8028000;
        end
        8'h3a: begin
            if ((lo >= 8'h04 && lo <= 8'h05) || (lo >= 8'h14 && lo <= 8'h15) || (lo >= 8'h24 && lo <= 8'h25) || (lo >= 8'h34 && lo <= 8'h35) || (lo >= 8'h44 && lo <= 8'h45) || (lo >= 8'h54 && lo <= 8'h55) || (lo >= 8'h64 && lo <= 8'h65) || (lo >= 8'h74 && lo <= 8'h75) || (lo >= 8'h84 && lo <= 8'h85) || (lo >= 8'h94 && lo <= 8'h95) || (lo >= 8'ha4 && lo <= 8'ha5) || (lo >= 8'hb4 && lo <= 8'hb5) || (lo >= 8'hc4 && lo <= 8'hc5) || (lo >= 8'hd4 && lo <= 8'hd5) || (lo >= 8'he4 && lo <= 8'he5) || (lo >= 8'hf4 && lo <= 8'hf5)) z8k_dec = 35'h15188006;
            else if ((lo >= 8'h06 && lo <= 8'h07) || (lo >= 8'h16 && lo <= 8'h17) || (lo >= 8'h26 && lo <= 8'h27) || (lo >= 8'h36 && lo <= 8'h37) || (lo >= 8'h46 && lo <= 8'h47) || (lo >= 8'h56 && lo <= 8'h57) || (lo >= 8'h66 && lo <= 8'h67) || (lo >= 8'h76 && lo <= 8'h77) || (lo >= 8'h86 && lo <= 8'h87) || (lo >= 8'h96 && lo <= 8'h97) || (lo >= 8'ha6 && lo <= 8'ha7) || (lo >= 8'hb6 && lo <= 8'hb7) || (lo >= 8'hc6 && lo <= 8'hc7) || (lo >= 8'hd6 && lo <= 8'hd7) || (lo >= 8'he6 && lo <= 8'he7) || (lo >= 8'hf6 && lo <= 8'hf7)) z8k_dec = 35'h19188016;
            else if ((lo >= 8'h0c && lo <= 8'h0f) || (lo >= 8'h1c && lo <= 8'h1f) || (lo >= 8'h2c && lo <= 8'h2f) || (lo >= 8'h3c && lo <= 8'h3f) || (lo >= 8'h4c && lo <= 8'h4f) || (lo >= 8'h5c && lo <= 8'h5f) || (lo >= 8'h6c && lo <= 8'h6f) || (lo >= 8'h7c && lo <= 8'h7f) || (lo >= 8'h8c && lo <= 8'h8f) || (lo >= 8'h9c && lo <= 8'h9f) || (lo >= 8'hac && lo <= 8'haf) || (lo >= 8'hbc && lo <= 8'hbf) || (lo >= 8'hcc && lo <= 8'hcf) || (lo >= 8'hdc && lo <= 8'hdf) || (lo >= 8'hec && lo <= 8'hef) || lo >= 8'hfc) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h2b188046;
        end
        8'h3b: begin
            if ((lo >= 8'h04 && lo <= 8'h05) || (lo >= 8'h14 && lo <= 8'h15) || (lo >= 8'h24 && lo <= 8'h25) || (lo >= 8'h34 && lo <= 8'h35) || (lo >= 8'h44 && lo <= 8'h45) || (lo >= 8'h54 && lo <= 8'h55) || (lo >= 8'h64 && lo <= 8'h65) || (lo >= 8'h74 && lo <= 8'h75) || (lo >= 8'h84 && lo <= 8'h85) || (lo >= 8'h94 && lo <= 8'h95) || (lo >= 8'ha4 && lo <= 8'ha5) || (lo >= 8'hb4 && lo <= 8'hb5) || (lo >= 8'hc4 && lo <= 8'hc5) || (lo >= 8'hd4 && lo <= 8'hd5) || (lo >= 8'he4 && lo <= 8'he5) || (lo >= 8'hf4 && lo <= 8'hf5)) z8k_dec = 35'h191a8006;
            else if ((lo >= 8'h06 && lo <= 8'h07) || (lo >= 8'h16 && lo <= 8'h17) || (lo >= 8'h26 && lo <= 8'h27) || (lo >= 8'h36 && lo <= 8'h37) || (lo >= 8'h46 && lo <= 8'h47) || (lo >= 8'h56 && lo <= 8'h57) || (lo >= 8'h66 && lo <= 8'h67) || (lo >= 8'h76 && lo <= 8'h77) || (lo >= 8'h86 && lo <= 8'h87) || (lo >= 8'h96 && lo <= 8'h97) || (lo >= 8'ha6 && lo <= 8'ha7) || (lo >= 8'hb6 && lo <= 8'hb7) || (lo >= 8'hc6 && lo <= 8'hc7) || (lo >= 8'hd6 && lo <= 8'hd7) || (lo >= 8'he6 && lo <= 8'he7) || (lo >= 8'hf6 && lo <= 8'hf7)) z8k_dec = 35'h191a8016;
            else if ((lo >= 8'h0c && lo <= 8'h0f) || (lo >= 8'h1c && lo <= 8'h1f) || (lo >= 8'h2c && lo <= 8'h2f) || (lo >= 8'h3c && lo <= 8'h3f) || (lo >= 8'h4c && lo <= 8'h4f) || (lo >= 8'h5c && lo <= 8'h5f) || (lo >= 8'h6c && lo <= 8'h6f) || (lo >= 8'h7c && lo <= 8'h7f) || (lo >= 8'h8c && lo <= 8'h8f) || (lo >= 8'h9c && lo <= 8'h9f) || (lo >= 8'hac && lo <= 8'haf) || (lo >= 8'hbc && lo <= 8'hbf) || (lo >= 8'hcc && lo <= 8'hcf) || (lo >= 8'hdc && lo <= 8'hdf) || (lo >= 8'hec && lo <= 8'hef) || lo >= 8'hfc) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h2b1a8046;
        end
        8'h3c: begin
             z8k_dec = 35'h15188022;
        end
        8'h3d: begin
             z8k_dec = 35'h151a8022;
        end
        8'h3e: begin
             z8k_dec = 35'h19188032;
        end
        8'h3f: begin
             z8k_dec = 35'h191a8032;
        end
        8'h40: begin
            if (lo <= 8'h0f) z8k_dec = 35'h12080304;
            else z8k_dec = 35'h14080404;
        end
        8'h41: begin
            if (lo <= 8'h0f) z8k_dec = 35'h120a0304;
            else z8k_dec = 35'h140a0404;
        end
        8'h42: begin
            if (lo <= 8'h0f) z8k_dec = 35'h12082304;
            else z8k_dec = 35'h14082404;
        end
        8'h43: begin
            if (lo <= 8'h0f) z8k_dec = 35'h120a2304;
            else z8k_dec = 35'h140a2404;
        end
        8'h44: begin
            if (lo <= 8'h0f) z8k_dec = 35'h12084304;
            else z8k_dec = 35'h14084404;
        end
        8'h45: begin
            if (lo <= 8'h0f) z8k_dec = 35'h120a4304;
            else z8k_dec = 35'h140a4404;
        end
        8'h46: begin
            if (lo <= 8'h0f) z8k_dec = 35'h12085304;
            else z8k_dec = 35'h14085404;
        end
        8'h47: begin
            if (lo <= 8'h0f) z8k_dec = 35'h120a5304;
            else z8k_dec = 35'h140a5404;
        end
        8'h48: begin
            if (lo <= 8'h0f) z8k_dec = 35'h12086304;
            else z8k_dec = 35'h14086404;
        end
        8'h49: begin
            if (lo <= 8'h0f) z8k_dec = 35'h120a6304;
            else z8k_dec = 35'h140a6404;
        end
        8'h4a: begin
            if (lo <= 8'h0f) z8k_dec = 35'h12087304;
            else z8k_dec = 35'h14087404;
        end
        8'h4b: begin
            if (lo <= 8'h0f) z8k_dec = 35'h120a7304;
            else z8k_dec = 35'h140a7404;
        end
        8'h4c: begin
            if (lo == 8'h00) z8k_dec = 35'h1e209324;
            else if (lo == 8'h01) z8k_dec = 35'h1c20f308;
            else if (lo == 8'h02) z8k_dec = 35'h1e20a304;
            else if (lo == 8'h04) z8k_dec = 35'h1620b304;
            else if (lo == 8'h05) z8k_dec = 35'h1c20e308;
            else if (lo == 8'h06) z8k_dec = 35'h1c20c304;
            else if (lo == 8'h08) z8k_dec = 35'h1620d304;
            else if (lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h20209404;
            else if (lo == 8'h11 || lo == 8'h21 || lo == 8'h31 || lo == 8'h41 || lo == 8'h51 || lo == 8'h61 || lo == 8'h71 || lo == 8'h81 || lo == 8'h91 || lo == 8'ha1 || lo == 8'hb1 || lo == 8'hc1 || lo == 8'hd1 || lo == 8'he1 || lo == 8'hf1) z8k_dec = 35'h1e20f408;
            else if (lo == 8'h12 || lo == 8'h22 || lo == 8'h32 || lo == 8'h42 || lo == 8'h52 || lo == 8'h62 || lo == 8'h72 || lo == 8'h82 || lo == 8'h92 || lo == 8'ha2 || lo == 8'hb2 || lo == 8'hc2 || lo == 8'hd2 || lo == 8'he2 || lo == 8'hf2) z8k_dec = 35'h2020a404;
            else if (lo == 8'h14 || lo == 8'h24 || lo == 8'h34 || lo == 8'h44 || lo == 8'h54 || lo == 8'h64 || lo == 8'h74 || lo == 8'h84 || lo == 8'h94 || lo == 8'ha4 || lo == 8'hb4 || lo == 8'hc4 || lo == 8'hd4 || lo == 8'he4 || lo == 8'hf4) z8k_dec = 35'h1820b404;
            else if (lo == 8'h15 || lo == 8'h25 || lo == 8'h35 || lo == 8'h45 || lo == 8'h55 || lo == 8'h65 || lo == 8'h75 || lo == 8'h85 || lo == 8'h95 || lo == 8'ha5 || lo == 8'hb5 || lo == 8'hc5 || lo == 8'hd5 || lo == 8'he5 || lo == 8'hf5) z8k_dec = 35'h1e20e408;
            else if (lo == 8'h16 || lo == 8'h26 || lo == 8'h36 || lo == 8'h46 || lo == 8'h56 || lo == 8'h66 || lo == 8'h76 || lo == 8'h86 || lo == 8'h96 || lo == 8'ha6 || lo == 8'hb6 || lo == 8'hc6 || lo == 8'hd6 || lo == 8'he6 || lo == 8'hf6) z8k_dec = 35'h1e20c404;
            else if (lo == 8'h18 || lo == 8'h28 || lo == 8'h38 || lo == 8'h48 || lo == 8'h58 || lo == 8'h68 || lo == 8'h78 || lo == 8'h88 || lo == 8'h98 || lo == 8'ha8 || lo == 8'hb8 || lo == 8'hc8 || lo == 8'hd8 || lo == 8'he8 || lo == 8'hf8) z8k_dec = 35'h1820d404;
            else z8k_dec = 35'h8028000;
        end
        8'h4d: begin
            if (lo == 8'h00) z8k_dec = 35'h1e229304;
            else if (lo == 8'h01) z8k_dec = 35'h1c22f308;
            else if (lo == 8'h02) z8k_dec = 35'h1e22a304;
            else if (lo == 8'h04) z8k_dec = 35'h1622b304;
            else if (lo == 8'h05) z8k_dec = 35'h1c22e308;
            else if (lo == 8'h06) z8k_dec = 35'h1c22c304;
            else if (lo == 8'h08) z8k_dec = 35'h1622d304;
            else if (lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h20229404;
            else if (lo == 8'h11 || lo == 8'h21 || lo == 8'h31 || lo == 8'h41 || lo == 8'h51 || lo == 8'h61 || lo == 8'h71 || lo == 8'h81 || lo == 8'h91 || lo == 8'ha1 || lo == 8'hb1 || lo == 8'hc1 || lo == 8'hd1 || lo == 8'he1 || lo == 8'hf1) z8k_dec = 35'h1e22f408;
            else if (lo == 8'h12 || lo == 8'h22 || lo == 8'h32 || lo == 8'h42 || lo == 8'h52 || lo == 8'h62 || lo == 8'h72 || lo == 8'h82 || lo == 8'h92 || lo == 8'ha2 || lo == 8'hb2 || lo == 8'hc2 || lo == 8'hd2 || lo == 8'he2 || lo == 8'hf2) z8k_dec = 35'h2022a404;
            else if (lo == 8'h14 || lo == 8'h24 || lo == 8'h34 || lo == 8'h44 || lo == 8'h54 || lo == 8'h64 || lo == 8'h74 || lo == 8'h84 || lo == 8'h94 || lo == 8'ha4 || lo == 8'hb4 || lo == 8'hc4 || lo == 8'hd4 || lo == 8'he4 || lo == 8'hf4) z8k_dec = 35'h1822b404;
            else if (lo == 8'h15 || lo == 8'h25 || lo == 8'h35 || lo == 8'h45 || lo == 8'h55 || lo == 8'h65 || lo == 8'h75 || lo == 8'h85 || lo == 8'h95 || lo == 8'ha5 || lo == 8'hb5 || lo == 8'hc5 || lo == 8'hd5 || lo == 8'he5 || lo == 8'hf5) z8k_dec = 35'h1e22e408;
            else if (lo == 8'h16 || lo == 8'h26 || lo == 8'h36 || lo == 8'h46 || lo == 8'h56 || lo == 8'h66 || lo == 8'h76 || lo == 8'h86 || lo == 8'h96 || lo == 8'ha6 || lo == 8'hb6 || lo == 8'hc6 || lo == 8'hd6 || lo == 8'he6 || lo == 8'hf6) z8k_dec = 35'h1e22c404;
            else if (lo == 8'h18 || lo == 8'h28 || lo == 8'h38 || lo == 8'h48 || lo == 8'h58 || lo == 8'h68 || lo == 8'h78 || lo == 8'h88 || lo == 8'h98 || lo == 8'ha8 || lo == 8'hb8 || lo == 8'hc8 || lo == 8'hd8 || lo == 8'he8 || lo == 8'hf8) z8k_dec = 35'h1822d404;
            else z8k_dec = 35'h8028000;
        end
        8'h4e: begin
            if (lo == 8'h11 || lo == 8'h21 || lo == 8'h31 || lo == 8'h41 || lo == 8'h51 || lo == 8'h61 || lo == 8'h71 || lo == 8'h81 || lo == 8'h91 || lo == 8'ha1 || lo == 8'hb1 || lo == 8'hc1 || lo == 8'hd1 || lo == 8'he1) z8k_dec = 35'h18308404;
            else z8k_dec = 35'h8028000;
        end
        8'h50: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1e0c7304;
            else z8k_dec = 35'h200c7404;
        end
        8'h51: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else if (lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h2a448304;
            else z8k_dec = 35'h2a448404;
        end
        8'h52: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1e0c2304;
            else z8k_dec = 35'h200c2404;
        end
        8'h53: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else if (lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h1c428304;
            else z8k_dec = 35'h1c428404;
        end
        8'h54: begin
            if (lo <= 8'h0f) z8k_dec = 35'h180c8304;
            else z8k_dec = 35'h1a0c8404;
        end
        8'h55: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else if (lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h2e4c8304;
            else z8k_dec = 35'h2e4c8404;
        end
        8'h56: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1e0c0304;
            else z8k_dec = 35'h200c0404;
        end
        8'h57: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else if (lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h204a8304;
            else z8k_dec = 35'h204a8404;
        end
        8'h58: begin
            if (lo <= 8'h0f) z8k_dec = 35'h236148304;
            else z8k_dec = 35'h238148404;
        end
        8'h59: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8e128304;
            else z8k_dec = 35'h90128404;
        end
        8'h5a: begin
            if (lo <= 8'h0f) z8k_dec = 35'h5d21c8304;
            else z8k_dec = 35'h5d41c8404;
        end
        8'h5b: begin
            if (lo <= 8'h0f) z8k_dec = 35'hd81a8304;
            else z8k_dec = 35'hda1a8404;
        end
        8'h5c: begin
            if (lo == 8'h01) z8k_dec = 35'h1d128318;
            else if (lo == 8'h08) z8k_dec = 35'h2024b304;
            else if (lo == 8'h09) z8k_dec = 35'h1d128308;
            else if (lo == 8'h11 || lo == 8'h21 || lo == 8'h31 || lo == 8'h41 || lo == 8'h51 || lo == 8'h61 || lo == 8'h71 || lo == 8'h81 || lo == 8'h91 || lo == 8'ha1 || lo == 8'hb1 || lo == 8'hc1 || lo == 8'hd1 || lo == 8'he1 || lo == 8'hf1) z8k_dec = 35'h1f128418;
            else if (lo == 8'h18 || lo == 8'h28 || lo == 8'h38 || lo == 8'h48 || lo == 8'h58 || lo == 8'h68 || lo == 8'h78 || lo == 8'h88 || lo == 8'h98 || lo == 8'ha8 || lo == 8'hb8 || lo == 8'hc8 || lo == 8'hd8 || lo == 8'he8 || lo == 8'hf8) z8k_dec = 35'h2224b404;
            else if (lo == 8'h19 || lo == 8'h29 || lo == 8'h39 || lo == 8'h49 || lo == 8'h59 || lo == 8'h69 || lo == 8'h79 || lo == 8'h89 || lo == 8'h99 || lo == 8'ha9 || lo == 8'hb9 || lo == 8'hc9 || lo == 8'hd9 || lo == 8'he9 || lo == 8'hf9) z8k_dec = 35'h1f128408;
            else z8k_dec = 35'h8028000;
        end
        8'h5d: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1e348304;
            else z8k_dec = 35'h1c348404;
        end
        8'h5e: begin
            if (lo <= 8'h0f) z8k_dec = 35'he5a8304;
            else z8k_dec = 35'h105a8404;
        end
        8'h5f: begin
            if (lo == 8'h00) z8k_dec = 35'h18628304;
            else if (lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h1a628404;
            else z8k_dec = 35'h8028000;
        end
        8'h60: begin
            if (lo <= 8'h0f) z8k_dec = 35'h12088304;
            else z8k_dec = 35'h14088404;
        end
        8'h61: begin
            if (lo <= 8'h0f) z8k_dec = 35'h120a8304;
            else z8k_dec = 35'h140a8404;
        end
        8'h62: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1a212304;
            else z8k_dec = 35'h1c212404;
        end
        8'h63: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1a232304;
            else z8k_dec = 35'h1c232404;
        end
        8'h64: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1a213304;
            else z8k_dec = 35'h1c213404;
        end
        8'h65: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1a233304;
            else z8k_dec = 35'h1c233404;
        end
        8'h66: begin
            if (lo <= 8'h0f) z8k_dec = 35'h14214304;
            else z8k_dec = 35'h16214404;
        end
        8'h67: begin
            if (lo <= 8'h0f) z8k_dec = 35'h14234304;
            else z8k_dec = 35'h16234404;
        end
        8'h68: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1a210304;
            else z8k_dec = 35'h1c210404;
        end
        8'h69: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1a230304;
            else z8k_dec = 35'h1c230404;
        end
        8'h6a: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1a211304;
            else z8k_dec = 35'h1c211404;
        end
        8'h6b: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1a231304;
            else z8k_dec = 35'h1c231404;
        end
        8'h6c: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1e388304;
            else z8k_dec = 35'h20388404;
        end
        8'h6d: begin
            if (lo <= 8'h0f) z8k_dec = 35'h1e3a8304;
            else z8k_dec = 35'h203a8404;
        end
        8'h6e: begin
            if (lo <= 8'h0f) z8k_dec = 35'h16308304;
            else z8k_dec = 35'h16308404;
        end
        8'h6f: begin
            if (lo <= 8'h0f) z8k_dec = 35'h16328304;
            else z8k_dec = 35'h18328404;
        end
        8'h70: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h1c088804;
        end
        8'h71: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h1c0a8804;
        end
        8'h72: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h1c308804;
        end
        8'h73: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h1c328804;
        end
        8'h74: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h1e528024;
        end
        8'h75: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h220c8804;
        end
        8'h76: begin
            if (lo <= 8'h0f) z8k_dec = 35'h18528034;
            else z8k_dec = 35'h1a528044;
        end
        8'h77: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h22348804;
        end
        8'h78: begin
             z8k_dec = 35'h14028000;
        end
        8'h79: begin
            if (lo == 8'h00) z8k_dec = 35'h20928306;
            else if (lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h22928406;
            else z8k_dec = 35'h8028000;
        end
        8'h7a: begin
            if (lo == 8'h00) z8k_dec = 35'h109a8002;
            else z8k_dec = 35'h8028000;
        end
        8'h7b: begin
            if (lo == 8'h00) z8k_dec = 35'h1a8a8002;
            else if ((lo >= 8'h08 && lo <= 8'h09)) z8k_dec = 35'ha028002;
            else if (lo == 8'h0a) z8k_dec = 35'he028002;
            else if (lo == 8'h0d || lo == 8'h1d || lo == 8'h2d || lo == 8'h3d || lo == 8'h4d || lo == 8'h5d || lo == 8'h6d || lo == 8'h7d || lo == 8'h8d || lo == 8'h9d || lo == 8'had || lo == 8'hbd || lo == 8'hcd || lo == 8'hdd || lo == 8'hed || lo == 8'hfd) z8k_dec = 35'h18b28002;
            else z8k_dec = 35'h8028000;
        end
        8'h7c: begin
            if (lo <= 8'h03) z8k_dec = 35'hea28002;
            else if ((lo >= 8'h04 && lo <= 8'h07)) z8k_dec = 35'hea28012;
            else z8k_dec = 35'h8028000;
        end
        8'h7d: begin
            if ((lo >= 8'h08 && lo <= 8'h0f) || (lo >= 8'h18 && lo <= 8'h1f) || (lo >= 8'h28 && lo <= 8'h2f) || (lo >= 8'h38 && lo <= 8'h3f) || (lo >= 8'h48 && lo <= 8'h4f) || (lo >= 8'h58 && lo <= 8'h5f) || (lo >= 8'h68 && lo <= 8'h6f) || (lo >= 8'h78 && lo <= 8'h7f) || (lo >= 8'h88 && lo <= 8'h8f) || (lo >= 8'h98 && lo <= 8'h9f) || (lo >= 8'ha8 && lo <= 8'haf) || (lo >= 8'hb8 && lo <= 8'hbf) || (lo >= 8'hc8 && lo <= 8'hcf) || (lo >= 8'hd8 && lo <= 8'hdf) || (lo >= 8'he8 && lo <= 8'hef) || lo >= 8'hf8) z8k_dec = 35'heaa8012;
            else z8k_dec = 35'heaa8002;
        end
        8'h7e: begin
             z8k_dec = 35'h14028000;
        end
        8'h7f: begin
             z8k_dec = 35'h42ba8000;
        end
        8'h80: begin
             z8k_dec = 35'h8080500;
        end
        8'h81: begin
             z8k_dec = 35'h80a0500;
        end
        8'h82: begin
             z8k_dec = 35'h8082500;
        end
        8'h83: begin
             z8k_dec = 35'h80a2500;
        end
        8'h84: begin
             z8k_dec = 35'h8084500;
        end
        8'h85: begin
             z8k_dec = 35'h80a4500;
        end
        8'h86: begin
             z8k_dec = 35'h8085500;
        end
        8'h87: begin
             z8k_dec = 35'h80a5500;
        end
        8'h88: begin
             z8k_dec = 35'h8086500;
        end
        8'h89: begin
             z8k_dec = 35'h80a6500;
        end
        8'h8a: begin
             z8k_dec = 35'h8087500;
        end
        8'h8b: begin
             z8k_dec = 35'h80a7500;
        end
        8'h8c: begin
            if (lo == 8'h00 || lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'he209500;
            else if (lo == 8'h01 || lo == 8'h11 || lo == 8'h21 || lo == 8'h31 || lo == 8'h41 || lo == 8'h51 || lo == 8'h61 || lo == 8'h71 || lo == 8'h81 || lo == 8'h91 || lo == 8'ha1 || lo == 8'hb1 || lo == 8'hc1 || lo == 8'hd1 || lo == 8'he1 || lo == 8'hf1) z8k_dec = 35'hec28030;
            else if (lo == 8'h02 || lo == 8'h12 || lo == 8'h22 || lo == 8'h32 || lo == 8'h42 || lo == 8'h52 || lo == 8'h62 || lo == 8'h72 || lo == 8'h82 || lo == 8'h92 || lo == 8'ha2 || lo == 8'hb2 || lo == 8'hc2 || lo == 8'hd2 || lo == 8'he2 || lo == 8'hf2) z8k_dec = 35'he20a500;
            else if (lo == 8'h04 || lo == 8'h14 || lo == 8'h24 || lo == 8'h34 || lo == 8'h44 || lo == 8'h54 || lo == 8'h64 || lo == 8'h74 || lo == 8'h84 || lo == 8'h94 || lo == 8'ha4 || lo == 8'hb4 || lo == 8'hc4 || lo == 8'hd4 || lo == 8'he4 || lo == 8'hf4) z8k_dec = 35'he20b500;
            else if (lo == 8'h06 || lo == 8'h16 || lo == 8'h26 || lo == 8'h36 || lo == 8'h46 || lo == 8'h56 || lo == 8'h66 || lo == 8'h76 || lo == 8'h86 || lo == 8'h96 || lo == 8'ha6 || lo == 8'hb6 || lo == 8'hc6 || lo == 8'hd6 || lo == 8'he6 || lo == 8'hf6) z8k_dec = 35'he20c500;
            else if (lo == 8'h08 || lo == 8'h18 || lo == 8'h28 || lo == 8'h38 || lo == 8'h48 || lo == 8'h58 || lo == 8'h68 || lo == 8'h78 || lo == 8'h88 || lo == 8'h98 || lo == 8'ha8 || lo == 8'hb8 || lo == 8'hc8 || lo == 8'hd8 || lo == 8'he8 || lo == 8'hf8) z8k_dec = 35'he20d500;
            else if (lo == 8'h09 || lo == 8'h19 || lo == 8'h29 || lo == 8'h39 || lo == 8'h49 || lo == 8'h59 || lo == 8'h69 || lo == 8'h79 || lo == 8'h89 || lo == 8'h99 || lo == 8'ha9 || lo == 8'hb9 || lo == 8'hc9 || lo == 8'hd9 || lo == 8'he9 || lo == 8'hf9) z8k_dec = 35'hec28040;
            else z8k_dec = 35'h8028000;
        end
        8'h8d: begin
            if (lo == 8'h00 || lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'he229500;
            else if (lo == 8'h01 || lo == 8'h11 || lo == 8'h21 || lo == 8'h31 || lo == 8'h41 || lo == 8'h51 || lo == 8'h61 || lo == 8'h71 || lo == 8'h81 || lo == 8'h91 || lo == 8'ha1 || lo == 8'hb1 || lo == 8'hc1 || lo == 8'hd1 || lo == 8'he1 || lo == 8'hf1) z8k_dec = 35'hec28000;
            else if (lo == 8'h02 || lo == 8'h12 || lo == 8'h22 || lo == 8'h32 || lo == 8'h42 || lo == 8'h52 || lo == 8'h62 || lo == 8'h72 || lo == 8'h82 || lo == 8'h92 || lo == 8'ha2 || lo == 8'hb2 || lo == 8'hc2 || lo == 8'hd2 || lo == 8'he2 || lo == 8'hf2) z8k_dec = 35'he22a500;
            else if (lo == 8'h03 || lo == 8'h13 || lo == 8'h23 || lo == 8'h33 || lo == 8'h43 || lo == 8'h53 || lo == 8'h63 || lo == 8'h73 || lo == 8'h83 || lo == 8'h93 || lo == 8'ha3 || lo == 8'hb3 || lo == 8'hc3 || lo == 8'hd3 || lo == 8'he3 || lo == 8'hf3) z8k_dec = 35'hec28010;
            else if (lo == 8'h04 || lo == 8'h14 || lo == 8'h24 || lo == 8'h34 || lo == 8'h44 || lo == 8'h54 || lo == 8'h64 || lo == 8'h74 || lo == 8'h84 || lo == 8'h94 || lo == 8'ha4 || lo == 8'hb4 || lo == 8'hc4 || lo == 8'hd4 || lo == 8'he4 || lo == 8'hf4) z8k_dec = 35'he22b500;
            else if (lo == 8'h05 || lo == 8'h15 || lo == 8'h25 || lo == 8'h35 || lo == 8'h45 || lo == 8'h55 || lo == 8'h65 || lo == 8'h75 || lo == 8'h85 || lo == 8'h95 || lo == 8'ha5 || lo == 8'hb5 || lo == 8'hc5 || lo == 8'hd5 || lo == 8'he5 || lo == 8'hf5) z8k_dec = 35'hec28020;
            else if (lo == 8'h06 || lo == 8'h16 || lo == 8'h26 || lo == 8'h36 || lo == 8'h46 || lo == 8'h56 || lo == 8'h66 || lo == 8'h76 || lo == 8'h86 || lo == 8'h96 || lo == 8'ha6 || lo == 8'hb6 || lo == 8'hc6 || lo == 8'hd6 || lo == 8'he6 || lo == 8'hf6) z8k_dec = 35'he22c500;
            else if (lo == 8'h07) z8k_dec = 35'he028000;
            else if (lo == 8'h08 || lo == 8'h18 || lo == 8'h28 || lo == 8'h38 || lo == 8'h48 || lo == 8'h58 || lo == 8'h68 || lo == 8'h78 || lo == 8'h88 || lo == 8'h98 || lo == 8'ha8 || lo == 8'hb8 || lo == 8'hc8 || lo == 8'hd8 || lo == 8'he8 || lo == 8'hf8) z8k_dec = 35'he22d500;
            else z8k_dec = 35'h8028000;
        end
        8'h8e: begin
             z8k_dec = 35'h15228001;
        end
        8'h8f: begin
             z8k_dec = 35'h15228001;
        end
        8'h90: begin
             z8k_dec = 35'h100c7500;
        end
        8'h91: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h18448500;
        end
        8'h92: begin
             z8k_dec = 35'h100c2500;
        end
        8'h93: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h12428500;
        end
        8'h94: begin
             z8k_dec = 35'ha0c8500;
        end
        8'h95: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h184c8500;
        end
        8'h96: begin
             z8k_dec = 35'h100c0500;
        end
        8'h97: begin
            if (lo <= 8'h0f) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h104a8500;
        end
        8'h98: begin
             z8k_dec = 35'h234148500;
        end
        8'h99: begin
             z8k_dec = 35'h8c128500;
        end
        8'h9a: begin
             z8k_dec = 35'h5d01c8500;
        end
        8'h9b: begin
             z8k_dec = 35'hd61a8500;
        end
        8'h9c: begin
            if (lo == 8'h00 || lo == 8'h08 || lo == 8'h10 || lo == 8'h18 || lo == 8'h20 || lo == 8'h28 || lo == 8'h30 || lo == 8'h38 || lo == 8'h40 || lo == 8'h48 || lo == 8'h50 || lo == 8'h58 || lo == 8'h60 || lo == 8'h68 || lo == 8'h70 || lo == 8'h78 || lo == 8'h80 || lo == 8'h88 || lo == 8'h90 || lo == 8'h98 || lo == 8'ha0 || lo == 8'ha8 || lo == 8'hb0 || lo == 8'hb8 || lo == 8'hc0 || lo == 8'hc8 || lo == 8'hd0 || lo == 8'hd8 || lo == 8'he0 || lo == 8'he8 || lo == 8'hf0 || lo == 8'hf8) z8k_dec = 35'h1a24b500;
            else z8k_dec = 35'h8028000;
        end
        8'h9d: begin
             z8k_dec = 35'h14028000;
        end
        8'h9e: begin
            if (lo <= 8'h0f) z8k_dec = 35'h146a8000;
            else z8k_dec = 35'h8028000;
        end
        8'h9f: begin
             z8k_dec = 35'h14028000;
        end
        8'ha0: begin
             z8k_dec = 35'h6088500;
        end
        8'ha1: begin
             z8k_dec = 35'h60a8500;
        end
        8'ha2: begin
             z8k_dec = 35'h8212500;
        end
        8'ha3: begin
             z8k_dec = 35'h8232500;
        end
        8'ha4: begin
             z8k_dec = 35'h8213500;
        end
        8'ha5: begin
             z8k_dec = 35'h8233500;
        end
        8'ha6: begin
             z8k_dec = 35'h8214500;
        end
        8'ha7: begin
             z8k_dec = 35'h8234500;
        end
        8'ha8: begin
             z8k_dec = 35'h8210500;
        end
        8'ha9: begin
             z8k_dec = 35'h8230500;
        end
        8'haa: begin
             z8k_dec = 35'h8211500;
        end
        8'hab: begin
             z8k_dec = 35'h8231500;
        end
        8'hac: begin
             z8k_dec = 35'hc388500;
        end
        8'had: begin
             z8k_dec = 35'hc3a8500;
        end
        8'hae: begin
             z8k_dec = 35'hae08000;
        end
        8'haf: begin
             z8k_dec = 35'hae28000;
        end
        8'hb0: begin
            if (lo == 8'h00 || lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'had08000;
            else z8k_dec = 35'h8028000;
        end
        8'hb1: begin
            if (lo == 8'h00 || lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h16d88000;
            else if (lo == 8'h07 || lo == 8'h17 || lo == 8'h27 || lo == 8'h37 || lo == 8'h47 || lo == 8'h57 || lo == 8'h67 || lo == 8'h77 || lo == 8'h87 || lo == 8'h97 || lo == 8'ha7 || lo == 8'hb7 || lo == 8'hc7 || lo == 8'hd7 || lo == 8'he7 || lo == 8'hf7) z8k_dec = 35'h16dc8000;
            else if (lo == 8'h0a || lo == 8'h1a || lo == 8'h2a || lo == 8'h3a || lo == 8'h4a || lo == 8'h5a || lo == 8'h6a || lo == 8'h7a || lo == 8'h8a || lo == 8'h9a || lo == 8'haa || lo == 8'hba || lo == 8'hca || lo == 8'hda || lo == 8'hea || lo == 8'hfa) z8k_dec = 35'h16da8000;
            else z8k_dec = 35'h8028000;
        end
        8'hb2: begin
            if (lo == 8'h00 || lo == 8'h02 || lo == 8'h10 || lo == 8'h12 || lo == 8'h20 || lo == 8'h22 || lo == 8'h30 || lo == 8'h32 || lo == 8'h40 || lo == 8'h42 || lo == 8'h50 || lo == 8'h52 || lo == 8'h60 || lo == 8'h62 || lo == 8'h70 || lo == 8'h72 || lo == 8'h80 || lo == 8'h82 || lo == 8'h90 || lo == 8'h92 || lo == 8'ha0 || lo == 8'ha2 || lo == 8'hb0 || lo == 8'hb2 || lo == 8'hc0 || lo == 8'hc2 || lo == 8'hd0 || lo == 8'hd2 || lo == 8'he0 || lo == 8'he2 || lo == 8'hf0 || lo == 8'hf2) z8k_dec = 35'hcc88000;
            else if (lo == 8'h01 || lo == 8'h11 || lo == 8'h21 || lo == 8'h31 || lo == 8'h41 || lo == 8'h51 || lo == 8'h61 || lo == 8'h71 || lo == 8'h81 || lo == 8'h91 || lo == 8'ha1 || lo == 8'hb1 || lo == 8'hc1 || lo == 8'hd1 || lo == 8'he1 || lo == 8'hf1) z8k_dec = 35'h1ac88044;
            else if (lo == 8'h03 || lo == 8'h13 || lo == 8'h23 || lo == 8'h33 || lo == 8'h43 || lo == 8'h53 || lo == 8'h63 || lo == 8'h73 || lo == 8'h83 || lo == 8'h93 || lo == 8'ha3 || lo == 8'hb3 || lo == 8'hc3 || lo == 8'hd3 || lo == 8'he3 || lo == 8'hf3) z8k_dec = 35'h1ec88084;
            else if (lo == 8'h04 || lo == 8'h06 || lo == 8'h14 || lo == 8'h16 || lo == 8'h24 || lo == 8'h26 || lo == 8'h34 || lo == 8'h36 || lo == 8'h44 || lo == 8'h46 || lo == 8'h54 || lo == 8'h56 || lo == 8'h64 || lo == 8'h66 || lo == 8'h74 || lo == 8'h76 || lo == 8'h84 || lo == 8'h86 || lo == 8'h94 || lo == 8'h96 || lo == 8'ha4 || lo == 8'ha6 || lo == 8'hb4 || lo == 8'hb6 || lo == 8'hc4 || lo == 8'hc6 || lo == 8'hd4 || lo == 8'hd6 || lo == 8'he4 || lo == 8'he6 || lo == 8'hf4 || lo == 8'hf6) z8k_dec = 35'hcc88020;
            else if (lo == 8'h08 || lo == 8'h0a || lo == 8'h18 || lo == 8'h1a || lo == 8'h28 || lo == 8'h2a || lo == 8'h38 || lo == 8'h3a || lo == 8'h48 || lo == 8'h4a || lo == 8'h58 || lo == 8'h5a || lo == 8'h68 || lo == 8'h6a || lo == 8'h78 || lo == 8'h7a || lo == 8'h88 || lo == 8'h8a || lo == 8'h98 || lo == 8'h9a || lo == 8'ha8 || lo == 8'haa || lo == 8'hb8 || lo == 8'hba || lo == 8'hc8 || lo == 8'hca || lo == 8'hd8 || lo == 8'hda || lo == 8'he8 || lo == 8'hea || lo == 8'hf8 || lo == 8'hfa) z8k_dec = 35'h12c88010;
            else if (lo == 8'h09 || lo == 8'h19 || lo == 8'h29 || lo == 8'h39 || lo == 8'h49 || lo == 8'h59 || lo == 8'h69 || lo == 8'h79 || lo == 8'h89 || lo == 8'h99 || lo == 8'ha9 || lo == 8'hb9 || lo == 8'hc9 || lo == 8'hd9 || lo == 8'he9 || lo == 8'hf9) z8k_dec = 35'h1ac88054;
            else if (lo == 8'h0b || lo == 8'h1b || lo == 8'h2b || lo == 8'h3b || lo == 8'h4b || lo == 8'h5b || lo == 8'h6b || lo == 8'h7b || lo == 8'h8b || lo == 8'h9b || lo == 8'hab || lo == 8'hbb || lo == 8'hcb || lo == 8'hdb || lo == 8'heb || lo == 8'hfb) z8k_dec = 35'h1ec88074;
            else if (lo == 8'h0c || lo == 8'h0e || lo == 8'h1c || lo == 8'h1e || lo == 8'h2c || lo == 8'h2e || lo == 8'h3c || lo == 8'h3e || lo == 8'h4c || lo == 8'h4e || lo == 8'h5c || lo == 8'h5e || lo == 8'h6c || lo == 8'h6e || lo == 8'h7c || lo == 8'h7e || lo == 8'h8c || lo == 8'h8e || lo == 8'h9c || lo == 8'h9e || lo == 8'hac || lo == 8'hae || lo == 8'hbc || lo == 8'hbe || lo == 8'hcc || lo == 8'hce || lo == 8'hdc || lo == 8'hde || lo == 8'hec || lo == 8'hee || lo == 8'hfc || lo == 8'hfe) z8k_dec = 35'h12c88030;
            else z8k_dec = 35'h8028000;
        end
        8'hb3: begin
            if (lo == 8'h01 || lo == 8'h11 || lo == 8'h21 || lo == 8'h31 || lo == 8'h41 || lo == 8'h51 || lo == 8'h61 || lo == 8'h71 || lo == 8'h81 || lo == 8'h91 || lo == 8'ha1 || lo == 8'hb1 || lo == 8'hc1 || lo == 8'hd1 || lo == 8'he1 || lo == 8'hf1) z8k_dec = 35'h1aca8044;
            else if (lo == 8'h03 || lo == 8'h13 || lo == 8'h23 || lo == 8'h33 || lo == 8'h43 || lo == 8'h53 || lo == 8'h63 || lo == 8'h73 || lo == 8'h83 || lo == 8'h93 || lo == 8'ha3 || lo == 8'hb3 || lo == 8'hc3 || lo == 8'hd3 || lo == 8'he3 || lo == 8'hf3) z8k_dec = 35'h1eca8064;
            else if (lo == 8'h04 || lo == 8'h06 || lo == 8'h14 || lo == 8'h16 || lo == 8'h24 || lo == 8'h26 || lo == 8'h34 || lo == 8'h36 || lo == 8'h44 || lo == 8'h46 || lo == 8'h54 || lo == 8'h56 || lo == 8'h64 || lo == 8'h66 || lo == 8'h74 || lo == 8'h76 || lo == 8'h84 || lo == 8'h86 || lo == 8'h94 || lo == 8'h96 || lo == 8'ha4 || lo == 8'ha6 || lo == 8'hb4 || lo == 8'hb6 || lo == 8'hc4 || lo == 8'hc6 || lo == 8'hd4 || lo == 8'hd6 || lo == 8'he4 || lo == 8'he6 || lo == 8'hf4 || lo == 8'hf6) z8k_dec = 35'hcca8020;
            else if (lo == 8'h05 || lo == 8'h15 || lo == 8'h25 || lo == 8'h35 || lo == 8'h45 || lo == 8'h55 || lo == 8'h65 || lo == 8'h75 || lo == 8'h85 || lo == 8'h95 || lo == 8'ha5 || lo == 8'hb5 || lo == 8'hc5 || lo == 8'hd5 || lo == 8'he5 || lo == 8'hf5) z8k_dec = 35'h1acc8044;
            else if (lo == 8'h07 || lo == 8'h17 || lo == 8'h27 || lo == 8'h37 || lo == 8'h47 || lo == 8'h57 || lo == 8'h67 || lo == 8'h77 || lo == 8'h87 || lo == 8'h97 || lo == 8'ha7 || lo == 8'hb7 || lo == 8'hc7 || lo == 8'hd7 || lo == 8'he7 || lo == 8'hf7) z8k_dec = 35'h1ecc8064;
            else if (lo == 8'h08 || lo == 8'h0a || lo == 8'h18 || lo == 8'h1a || lo == 8'h28 || lo == 8'h2a || lo == 8'h38 || lo == 8'h3a || lo == 8'h48 || lo == 8'h4a || lo == 8'h58 || lo == 8'h5a || lo == 8'h68 || lo == 8'h6a || lo == 8'h78 || lo == 8'h7a || lo == 8'h88 || lo == 8'h8a || lo == 8'h98 || lo == 8'h9a || lo == 8'ha8 || lo == 8'haa || lo == 8'hb8 || lo == 8'hba || lo == 8'hc8 || lo == 8'hca || lo == 8'hd8 || lo == 8'hda || lo == 8'he8 || lo == 8'hea || lo == 8'hf8 || lo == 8'hfa) z8k_dec = 35'hcca8010;
            else if (lo == 8'h09 || lo == 8'h19 || lo == 8'h29 || lo == 8'h39 || lo == 8'h49 || lo == 8'h59 || lo == 8'h69 || lo == 8'h79 || lo == 8'h89 || lo == 8'h99 || lo == 8'ha9 || lo == 8'hb9 || lo == 8'hc9 || lo == 8'hd9 || lo == 8'he9 || lo == 8'hf9) z8k_dec = 35'h1aca8054;
            else if (lo == 8'h0b || lo == 8'h1b || lo == 8'h2b || lo == 8'h3b || lo == 8'h4b || lo == 8'h5b || lo == 8'h6b || lo == 8'h7b || lo == 8'h8b || lo == 8'h9b || lo == 8'hab || lo == 8'hbb || lo == 8'hcb || lo == 8'hdb || lo == 8'heb || lo == 8'hfb) z8k_dec = 35'h1eca8074;
            else if (lo == 8'h0c || lo == 8'h0e || lo == 8'h1c || lo == 8'h1e || lo == 8'h2c || lo == 8'h2e || lo == 8'h3c || lo == 8'h3e || lo == 8'h4c || lo == 8'h4e || lo == 8'h5c || lo == 8'h5e || lo == 8'h6c || lo == 8'h6e || lo == 8'h7c || lo == 8'h7e || lo == 8'h8c || lo == 8'h8e || lo == 8'h9c || lo == 8'h9e || lo == 8'hac || lo == 8'hae || lo == 8'hbc || lo == 8'hbe || lo == 8'hcc || lo == 8'hce || lo == 8'hdc || lo == 8'hde || lo == 8'hec || lo == 8'hee || lo == 8'hfc || lo == 8'hfe) z8k_dec = 35'hcca8030;
            else if (lo == 8'h0d || lo == 8'h1d || lo == 8'h2d || lo == 8'h3d || lo == 8'h4d || lo == 8'h5d || lo == 8'h6d || lo == 8'h7d || lo == 8'h8d || lo == 8'h9d || lo == 8'had || lo == 8'hbd || lo == 8'hcd || lo == 8'hdd || lo == 8'hed || lo == 8'hfd) z8k_dec = 35'h1acc8054;
            else if (lo == 8'h0f || lo == 8'h1f || lo == 8'h2f || lo == 8'h3f || lo == 8'h4f || lo == 8'h5f || lo == 8'h6f || lo == 8'h7f || lo == 8'h8f || lo == 8'h9f || lo == 8'haf || lo == 8'hbf || lo == 8'hcf || lo == 8'hdf || lo == 8'hef || lo == 8'hff) z8k_dec = 35'h1ecc8074;
            else z8k_dec = 35'hcca8000;
        end
        8'hb4: begin
             z8k_dec = 35'ha081500;
        end
        8'hb5: begin
             z8k_dec = 35'ha0a1500;
        end
        8'hb6: begin
             z8k_dec = 35'ha083500;
        end
        8'hb7: begin
             z8k_dec = 35'ha0a3500;
        end
        8'hb8: begin
            if (lo == 8'h10 || lo == 8'h12 || lo == 8'h14 || lo == 8'h16 || lo == 8'h18 || lo == 8'h1a || lo == 8'h1c || lo == 8'h1e || lo == 8'h20 || lo == 8'h22 || lo == 8'h24 || lo == 8'h26 || lo == 8'h28 || lo == 8'h2a || lo == 8'h2c || lo == 8'h2e || lo == 8'h30 || lo == 8'h32 || lo == 8'h34 || lo == 8'h36 || lo == 8'h38 || lo == 8'h3a || lo == 8'h3c || lo == 8'h3e || lo == 8'h40 || lo == 8'h42 || lo == 8'h44 || lo == 8'h46 || lo == 8'h48 || lo == 8'h4a || lo == 8'h4c || lo == 8'h4e || lo == 8'h50 || lo == 8'h52 || lo == 8'h54 || lo == 8'h56 || lo == 8'h58 || lo == 8'h5a || lo == 8'h5c || lo == 8'h5e || lo == 8'h60 || lo == 8'h62 || lo == 8'h64 || lo == 8'h66 || lo == 8'h68 || lo == 8'h6a || lo == 8'h6c || lo == 8'h6e || lo == 8'h70 || lo == 8'h72 || lo == 8'h74 || lo == 8'h76 || lo == 8'h78 || lo == 8'h7a || lo == 8'h7c || lo == 8'h7e || lo == 8'h80 || lo == 8'h82 || lo == 8'h84 || lo == 8'h86 || lo == 8'h88 || lo == 8'h8a || lo == 8'h8c || lo == 8'h8e || lo == 8'h90 || lo == 8'h92 || lo == 8'h94 || lo == 8'h96 || lo == 8'h98 || lo == 8'h9a || lo == 8'h9c || lo == 8'h9e || lo == 8'ha0 || lo == 8'ha2 || lo == 8'ha4 || lo == 8'ha6 || lo == 8'ha8 || lo == 8'haa || lo == 8'hac || lo == 8'hae || lo == 8'hb0 || lo == 8'hb2 || lo == 8'hb4 || lo == 8'hb6 || lo == 8'hb8 || lo == 8'hba || lo == 8'hbc || lo == 8'hbe || lo == 8'hc0 || lo == 8'hc2 || lo == 8'hc4 || lo == 8'hc6 || lo == 8'hc8 || lo == 8'hca || lo == 8'hcc || lo == 8'hce || lo == 8'hd0 || lo == 8'hd2 || lo == 8'hd4 || lo == 8'hd6 || lo == 8'hd8 || lo == 8'hda || lo == 8'hdc || lo == 8'hde || lo == 8'he0 || lo == 8'he2 || lo == 8'he4 || lo == 8'he6 || lo == 8'he8 || lo == 8'hea || lo == 8'hec || lo == 8'hee || lo == 8'hf0 || lo == 8'hf2 || lo == 8'hf4 || lo == 8'hf6 || lo == 8'hf8 || lo == 8'hfa || lo == 8'hfc || lo == 8'hfe) z8k_dec = 35'h33088004;
            else z8k_dec = 35'h8028000;
        end
        8'hb9: begin
            if (lo == 8'h00 || lo == 8'h10 || lo == 8'h20 || lo == 8'h30 || lo == 8'h40 || lo == 8'h50 || lo == 8'h60 || lo == 8'h70 || lo == 8'h80 || lo == 8'h90 || lo == 8'ha0 || lo == 8'hb0 || lo == 8'hc0 || lo == 8'hd0 || lo == 8'he0 || lo == 8'hf0) z8k_dec = 35'h14028000;
            else z8k_dec = 35'h8028000;
        end
        8'hba: begin
            if (lo <= 8'h0f || lo == 8'h13 || lo == 8'h15 || lo == 8'h17 || lo == 8'h1b || lo == 8'h1d || lo == 8'h1f || lo == 8'h23 || lo == 8'h25 || lo == 8'h27 || lo == 8'h2b || lo == 8'h2d || lo == 8'h2f || lo == 8'h33 || lo == 8'h35 || lo == 8'h37 || lo == 8'h3b || lo == 8'h3d || lo == 8'h3f || lo == 8'h43 || lo == 8'h45 || lo == 8'h47 || lo == 8'h4b || lo == 8'h4d || lo == 8'h4f || lo == 8'h53 || lo == 8'h55 || lo == 8'h57 || lo == 8'h5b || lo == 8'h5d || lo == 8'h5f || lo == 8'h63 || lo == 8'h65 || lo == 8'h67 || lo == 8'h6b || lo == 8'h6d || lo == 8'h6f || lo == 8'h73 || lo == 8'h75 || lo == 8'h77 || lo == 8'h7b || lo == 8'h7d || lo == 8'h7f || lo == 8'h83 || lo == 8'h85 || lo == 8'h87 || lo == 8'h8b || lo == 8'h8d || lo == 8'h8f || lo == 8'h93 || lo == 8'h95 || lo == 8'h97 || lo == 8'h9b || lo == 8'h9d || lo == 8'h9f || lo == 8'ha3 || lo == 8'ha5 || lo == 8'ha7 || lo == 8'hab || lo == 8'had || lo == 8'haf || lo == 8'hb3 || lo == 8'hb5 || lo == 8'hb7 || lo == 8'hbb || lo == 8'hbd || lo == 8'hbf || lo == 8'hc3 || lo == 8'hc5 || lo == 8'hc7 || lo == 8'hcb || lo == 8'hcd || lo == 8'hcf || lo == 8'hd3 || lo == 8'hd5 || lo == 8'hd7 || lo == 8'hdb || lo == 8'hdd || lo == 8'hdf || lo == 8'he3 || lo == 8'he5 || lo == 8'he7 || lo == 8'heb || lo == 8'hed || lo == 8'hef || lo == 8'hf3 || lo == 8'hf5 || lo == 8'hf7 || lo == 8'hfb || lo == 8'hfd || lo == 8'hff) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h17008004;
        end
        8'hbb: begin
            if (lo <= 8'h0f || lo == 8'h13 || lo == 8'h15 || lo == 8'h17 || lo == 8'h1b || lo == 8'h1d || lo == 8'h1f || lo == 8'h23 || lo == 8'h25 || lo == 8'h27 || lo == 8'h2b || lo == 8'h2d || lo == 8'h2f || lo == 8'h33 || lo == 8'h35 || lo == 8'h37 || lo == 8'h3b || lo == 8'h3d || lo == 8'h3f || lo == 8'h43 || lo == 8'h45 || lo == 8'h47 || lo == 8'h4b || lo == 8'h4d || lo == 8'h4f || lo == 8'h53 || lo == 8'h55 || lo == 8'h57 || lo == 8'h5b || lo == 8'h5d || lo == 8'h5f || lo == 8'h63 || lo == 8'h65 || lo == 8'h67 || lo == 8'h6b || lo == 8'h6d || lo == 8'h6f || lo == 8'h73 || lo == 8'h75 || lo == 8'h77 || lo == 8'h7b || lo == 8'h7d || lo == 8'h7f || lo == 8'h83 || lo == 8'h85 || lo == 8'h87 || lo == 8'h8b || lo == 8'h8d || lo == 8'h8f || lo == 8'h93 || lo == 8'h95 || lo == 8'h97 || lo == 8'h9b || lo == 8'h9d || lo == 8'h9f || lo == 8'ha3 || lo == 8'ha5 || lo == 8'ha7 || lo == 8'hab || lo == 8'had || lo == 8'haf || lo == 8'hb3 || lo == 8'hb5 || lo == 8'hb7 || lo == 8'hbb || lo == 8'hbd || lo == 8'hbf || lo == 8'hc3 || lo == 8'hc5 || lo == 8'hc7 || lo == 8'hcb || lo == 8'hcd || lo == 8'hcf || lo == 8'hd3 || lo == 8'hd5 || lo == 8'hd7 || lo == 8'hdb || lo == 8'hdd || lo == 8'hdf || lo == 8'he3 || lo == 8'he5 || lo == 8'he7 || lo == 8'heb || lo == 8'hed || lo == 8'hef || lo == 8'hf3 || lo == 8'hf5 || lo == 8'hf7 || lo == 8'hfb || lo == 8'hfd || lo == 8'hff) z8k_dec = 35'h8028000;
            else z8k_dec = 35'h17028004;
        end
        8'hbc: begin
             z8k_dec = 35'h12f88000;
        end
        8'hbd: begin
             z8k_dec = 35'haea8000;
        end
        8'hbe: begin
             z8k_dec = 35'h12f88010;
        end
        8'hbf: begin
             z8k_dec = 35'h14028000;
        end
        8'hc0: begin
             z8k_dec = 35'haf08000;
        end
        8'hc1: begin
             z8k_dec = 35'haf08000;
        end
        8'hc2: begin
             z8k_dec = 35'haf08000;
        end
        8'hc3: begin
             z8k_dec = 35'haf08000;
        end
        8'hc4: begin
             z8k_dec = 35'haf08000;
        end
        8'hc5: begin
             z8k_dec = 35'haf08000;
        end
        8'hc6: begin
             z8k_dec = 35'haf08000;
        end
        8'hc7: begin
             z8k_dec = 35'haf08000;
        end
        8'hc8: begin
             z8k_dec = 35'haf08000;
        end
        8'hc9: begin
             z8k_dec = 35'haf08000;
        end
        8'hca: begin
             z8k_dec = 35'haf08000;
        end
        8'hcb: begin
             z8k_dec = 35'haf08000;
        end
        8'hcc: begin
             z8k_dec = 35'haf08000;
        end
        8'hcd: begin
             z8k_dec = 35'haf08000;
        end
        8'hce: begin
             z8k_dec = 35'haf08000;
        end
        8'hcf: begin
             z8k_dec = 35'haf08000;
        end
        8'hd0: begin
             z8k_dec = 35'h14728000;
        end
        8'hd1: begin
             z8k_dec = 35'h14728000;
        end
        8'hd2: begin
             z8k_dec = 35'h14728000;
        end
        8'hd3: begin
             z8k_dec = 35'h14728000;
        end
        8'hd4: begin
             z8k_dec = 35'h14728000;
        end
        8'hd5: begin
             z8k_dec = 35'h14728000;
        end
        8'hd6: begin
             z8k_dec = 35'h14728000;
        end
        8'hd7: begin
             z8k_dec = 35'h14728000;
        end
        8'hd8: begin
             z8k_dec = 35'h14728000;
        end
        8'hd9: begin
             z8k_dec = 35'h14728000;
        end
        8'hda: begin
             z8k_dec = 35'h14728000;
        end
        8'hdb: begin
             z8k_dec = 35'h14728000;
        end
        8'hdc: begin
             z8k_dec = 35'h14728000;
        end
        8'hdd: begin
             z8k_dec = 35'h14728000;
        end
        8'hde: begin
             z8k_dec = 35'h14728000;
        end
        8'hdf: begin
             z8k_dec = 35'h14728000;
        end
        8'he0: begin
             z8k_dec = 35'hc7a8000;
        end
        8'he1: begin
             z8k_dec = 35'hc7a8000;
        end
        8'he2: begin
             z8k_dec = 35'hc7a8000;
        end
        8'he3: begin
             z8k_dec = 35'hc7a8000;
        end
        8'he4: begin
             z8k_dec = 35'hc7a8000;
        end
        8'he5: begin
             z8k_dec = 35'hc7a8000;
        end
        8'he6: begin
             z8k_dec = 35'hc7a8000;
        end
        8'he7: begin
             z8k_dec = 35'hc7a8000;
        end
        8'he8: begin
             z8k_dec = 35'hc7a8000;
        end
        8'he9: begin
             z8k_dec = 35'hc7a8000;
        end
        8'hea: begin
             z8k_dec = 35'hc7a8000;
        end
        8'heb: begin
             z8k_dec = 35'hc7a8000;
        end
        8'hec: begin
             z8k_dec = 35'hc7a8000;
        end
        8'hed: begin
             z8k_dec = 35'hc7a8000;
        end
        8'hee: begin
             z8k_dec = 35'hc7a8000;
        end
        8'hef: begin
             z8k_dec = 35'hc7a8000;
        end
        8'hf0: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hf1: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hf2: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hf3: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hf4: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hf5: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hf6: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hf7: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hf8: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hf9: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hfa: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hfb: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hfc: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hfd: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hfe: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        8'hff: begin
            if (lo >= 8'h80) z8k_dec = 35'h16828000;
            else z8k_dec = 35'h16808000;
        end
        default: ;
    endcase
endfunction

function automatic logic [8:0] z8k_dab(input logic [10:0] idx);
    logic [7:0] v, corr;
    logic       c, h, d, cout;
    v = idx[7:0];
    c = idx[8];
    h = idx[9];
    d = idx[10];
    if (!d) begin
        if (h || c) begin corr = 8'h66; cout = 1'b1; end
        else begin
            corr = ((v[3:0] > 4'd9) ? 8'h06 : 8'h00) + ((v > 8'h99) ? 8'h60 : 8'h00);
            cout = (v > 8'h99);
        end
    end else begin
        case ({h, c})
            2'b00: corr = 8'h00;
            2'b01: corr = 8'ha0;
            2'b10: corr = 8'hfa;
            default: corr = 8'h9a;
        endcase
        cout = h | c;
    end
    z8k_dab = {cout, v + corr};
endfunction
