#!/usr/bin/env python3
"""Build a standalone C++ reference model of MAME's Z8002 core.

MAME's opcode implementations (z8000ops.hxx) and dispatch table (z8000tbl.hxx)
are compiled verbatim. The device plumbing they sit in (memory_access, devcb,
logging) is replaced by a small shim, and the handful of z8000.cpp functions
the opcodes call are extracted from MAME's source text rather than retyped, so
the model cannot drift from the emulator it stands in for.

    gen_shim.py <mame_src_dir> <out_dir>
writes <out_dir>/z8k_ref_gen.cpp, compiled together with sim/z8002/z8k_ref.h.
"""
import os, re, sys

src, out = sys.argv[1], sys.argv[2]
os.makedirs(out, exist_ok=True)
cpp = open(os.path.join(src, 'z8000.cpp')).read()

# z8002_device functions to take from z8000.cpp (z8001 overrides are skipped;
# execute_run is re-expressed as step() in z8k_ref.h so the harness can run one
# loop iteration at a time).
WANT = ['addr_add', 'addr_sub', 'RDOP', 'get_operand', 'get_addr_operand',
        'get_raw_addr_operand', 'adjust_addr_for_nonseg_mode', 'RDMEM_B',
        'RDMEM_W', 'RDMEM_L', 'WRMEM_B', 'WRMEM_W', 'WRMEM_L', 'RDPORT_B',
        'RDPORT_W', 'WRPORT_B', 'WRPORT_W', 'cycles', 'PUSH_PC', 'GET_PC',
        'get_reset_pc', 'GET_FCW', 'F_SEG_Z8001', 'PSA_ADDR', 'Interrupt',
        'read_irq_vector', 'clear_internal_state', 'init_tables',
        'device_reset', 'execute_set_input', 'get_segmented_mode']


def extract(name):
    m = re.search(r'^[^\n]*\bz8002_device::' + name + r'\s*\([^\n]*\n\{', cpp, re.M)
    if not m:
        sys.exit('cannot find z8002_device::' + name)
    i = m.end()
    depth = 1
    while depth:
        c = cpp[i]
        depth += (c == '{') - (c == '}')
        i += 1
    return cpp[m.start():i]


body = []
body.append('// generated by sim/z8002/gen_shim.py from MAME 0.288 sources -- do not edit\n')
hdr = open(os.path.join(src, 'z8000.h')).read()
ops = sorted(set(re.findall(r'^\s*void (Z[0-9A-F][0-9A-Za-z_]*)\(\);', hdr, re.M)))
open(os.path.join(out, 'z8k_ref_ops.inc'), 'w').write(''.join('\tvoid %s();\n' % o for o in ops))
body.append('#include "z8k_ref.h"\n')
body.append('#include "z8000cpu.h"\n')
body.append('#include "z8000dab.h"\n')
for n in WANT:
    body.append(extract(n) + '\n')
body.append('#define printf(...) ((void)0)\n')
body.append('#include "z8000ops.hxx"\n')
body.append('#include "z8000tbl.hxx"\n')
body.append('''
// One iteration of execute_run()'s loop body (z8000.cpp). Returns true if an
// instruction was fetched and executed, false if the CPU is halted.
bool z8002_device::step()
{
	if (m_irq_req)
		Interrupt();
	m_ppc = m_pc;
	if (m_halt)
	{
		m_icount = 0;
		return false;
	}
	m_op[0] = RDOP();
	m_op_valid = 1;
	const Z8000_init &exec = table[z8000_exec[m_op[0]]];
	m_icount -= exec.cycles;
	(this->*exec.opcode)();
	m_op_valid = 0;
	return true;
}
''')
open(os.path.join(out, 'z8k_ref_gen.cpp'), 'w').write('\n'.join(body))
print('wrote', os.path.join(out, 'z8k_ref_gen.cpp'))
